export const PROFILE_SPORTS = [
  'Baseball',
  'Basketball',
  'Boxing',
  'Football',
  'Golf',
  'Lacrosse',
  'MMA',
  'Motocross',
  'Soccer',
  'Skiing',
  'Swimming',
  'Tennis',
  'Track & Field',
  'Volleyball',
  'Wrestling',
] as const;

export const SPORT_POSITIONS: Record<string, readonly string[]> = {
  Baseball: [
    'Pitcher',
    'Catcher',
    'First Base',
    'Second Base',
    'Shortstop',
    'Third Base',
    'Outfield',
  ],
  Basketball: ['Point Guard', 'Shooting Guard', 'Small Forward', 'Power Forward', 'Center'],
  Football: [
    'Quarterback',
    'Running Back',
    'Wide Receiver',
    'Tight End',
    'Offensive Line',
    'Defensive Line',
    'Linebacker',
    'Cornerback',
    'Safety',
  ],
  Lacrosse: ['Attack', 'Midfield', 'Defense', 'Goalie'],
  Soccer: ['Goalkeeper', 'Defender', 'Midfielder', 'Forward'],
  Volleyball: ['Setter', 'Outside Hitter', 'Middle Blocker', 'Opposite', 'Libero'],
  Wrestling: ['Lightweight', 'Middleweight', 'Heavyweight'],
};

export const US_STATES = [
  'AL',
  'AK',
  'AZ',
  'AR',
  'CA',
  'CO',
  'CT',
  'DE',
  'FL',
  'GA',
  'HI',
  'ID',
  'IL',
  'IN',
  'IA',
  'KS',
  'KY',
  'LA',
  'ME',
  'MD',
  'MA',
  'MI',
  'MN',
  'MS',
  'MO',
  'MT',
  'NE',
  'NV',
  'NH',
  'NJ',
  'NM',
  'NY',
  'NC',
  'ND',
  'OH',
  'OK',
  'OR',
  'PA',
  'RI',
  'SC',
  'SD',
  'TN',
  'TX',
  'UT',
  'VT',
  'VA',
  'WA',
  'WV',
  'WI',
  'WY',
] as const;
